# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dev-agentic-framework-cwa

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://agenticassistant.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_23f79cb8bc97486990ff38c7c40ba60a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_896c2ce1201c489ca7c376a5eb746f15 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: agenticassistant.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_23f79cb8bc97486990ff38c7c40ba60a }}/agenticassistant.azurecr.io/agenticassistant:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dev-agentic-framework-cwa'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2155cd9c42064f5cb6cf0d6ecb972ce2 }}
        images: 'agenticassistant.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_23f79cb8bc97486990ff38c7c40ba60a }}/agenticassistant.azurecr.io/agenticassistant:${{ github.sha }}'